
= PowerBuilder Manager
Simon Reichenbach <simon.reichenbach@informaticon.com>

== Abstract
This is a set of Python scripts that you can use to export and import source code from/into PowerBuilder.
In the future, this project will be expanded to include more tools for handling PowerBuilder source code.

The scripts can be used for other projects as well, but in most cases you will be interested in the command line tool pbmanager.
In this document, only the command line tool is covered.

== Installation

=== Binaries
This package is 

=== Build from Source

==== Requirements
* A Python 3 Interpreter (**x86**) with the following packages installed
** tabulate
** click
** pyinstaller

== Usage
In order to use this tool, you must have a working PowerBuilder installation (this tool uses the PBORCAxxx.dll).
The examples use the compiled version of this tool, but you can also run it from source (`pbmanager.py`).

.Show Help
[source,batch]
----
pbmanager.exe --help
----

=== Manual Import/Export from single PBL files

.Export source from PBL to folder
[source,batch]
----
:: files are exported to the subfolder .\src\<libraryName>\
pbmanager.exe export pbl "C:\a3\grundschicht\lib\inf1.pbl"
----

.Import source from folder into PBL
[source,batch]
----
:: files are imported from the subfolder .\src\<libraryName>\
pbmanager.exe import pbl "C:\a3\grundschicht\lib\inf1.pbl"
----

=== Automation / Integration

.Export source from a specific PBT (and all its PBL) to folder
[source,batch]
----
:: Export all objects
pbmanager.exe export pbt --type full "C:\a3\grundschicht\lib\a3.pbt"

:: Export only changed objects since last export
pbmanager.exe export pbt --type delta "C:\a3\grundschicht\lib\a3.pbt"
----

.Export source for all PBT files (and all their PBL) in a working tree to folder
[source,batch]
----
:: Export all objects
pbmanager.exe export folder --type full C:\a3\grundschicht\

:: Export only changed objects since last export
pbmanager.exe export folder --type delta C:\a3\grundschicht\
----
