name: GitHub and Choco release
on:
  push:
    branches:
      # make sure those branches match with step 'Increase version and push tag' to avoid releasing a package without
      # former tag creation (pre_release_branches: prerelease, release_branches: main)
      - main
      - prerelease
  workflow_dispatch:

jobs:
  createrelease:
    runs-on: self-hosted
    env:
      GOPRIVATE: github.com/informaticon/*

    steps:
      # Depth = 0 needed to determine version
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: './go.mod'
          cache: false

    
      - name: Git Creds
        run: git config --global url.https://`${{ secrets.GH_PRIVATE_READ_PAT }}@github.com/.insteadOf https://github.com/
        # ATTENTION: The config will persist, so after each workflow run the .gitconfig is removed by a 
        # powershell script under the environment variable ACTIONS_RUNNER_HOOK_JOB_COMPLETED.   
        # Make sure this is created at runner setup: https://slab.informaticon.com/posts/wip-add-own-git-hub-actions-runner-p3a0bxi3.
        
      # goes through commits and increases major if a commit msg body contains `BREAKING CHANGE:`,
      # increases minor if `feat:` found or increases patch on `fix:`
      # if none of them occur, the default can be set with default_bump (major, minor, patch, false)
      # set manually a version with "custom_tag" (https://github.com/mathieudutour/github-tag-action)
      - name: Increase version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ github.token }} # need write permissions to tag repo
          default_bump: false
          default_prerelease_bump: prerelease
          pre_release_branches: prerelease,dev_backport
          append_to_pre_release_tag: testrelease
        
      - name: assign runner environment variable SRVBUILDXY_PFX_FILE to PFX_FILE specifing the pfx file on the runner 
        run: echo "PFX_FILE=$env:SRVBUILDXY_PFX_FILE" >> $env:GITHUB_ENV

      - name: Choco release
        uses: informaticon/dev.github.base.go-choco-release@v2
        with:
          build_cmd: |
            $Env:GOOS = "windows"; $Env:GOARCH = "amd64"; go build -o ./choco/tools/pbmanager.exe -ldflags "-X 'github.com/informaticon/dev.win.base.pbmanager/cmd.Version=${{ steps.tag_version.outputs.new_version }}' -X 'github.com/informaticon/dev.win.base.pbmanager/cmd.BuildTime=$(Get-Date -Format "yyyy-MM-ddTHH:mm:sszzz")'"
          sign_cmd: |
            csb-cli ./choco/tools/pbmanager.exe --silent
          choco_pkg_name: pbmanager
          path_to_nuspec: ./choco/
          release_asset_files: |
            ./choco/pbmanager.exe
          choco_api_key: ${{ secrets.GITHUB_TOKEN }}
          codesigning_pfx: ${{ env.PFX_FILE }}
          codesigning_pfx_passphrase: ${{ secrets.SRVBUILDXY_PRIVATE_KEY_PASSPHRASE }}
          choco_registry: ${{ vars.CHOCO_REGISTRY }}
          new_version: '${{ steps.tag_version.outputs.new_version }}'
          release_type: '${{ steps.tag_version.outputs.release_type }}'
          new_tag: '${{ steps.tag_version.outputs.new_tag }}'
